<?php

/**
 * Links in Magento template should be generated using a block helper function getUrl()
 * To get access to our IDE's intellisense functionality, we will need to typehint this variable at the top of our template file.
 * 
 * ViewModel - Just like we have access to this $block variable, we can access our own
 *             custom variables in templates by passing them in as arguments to the block.
 * 
 * This below is a typehint
 *
 * @var Magento\Framework\View\Element\Template $block
 */

/**
 * We will also create one for this new $postVm to add intellisense lookups to this variale.
 * 
 * @var JonaM\Blog\ViewModel\Post $postVm
 */
$postVm = $block->getData('post_vm');
?>
<div class="blog-post-list">
    <!-- 
        Magento comes with a special PHP function we should pass all text through. 
        wrap this text in a short echo tag, and wrap it in this special function __()
        This function makes text translatable to many other languages. 
        Make it a practice to wrap all static texts this way
    -->
    <h1><?= __('Blog Post List'); ?></h1>
    <ul>
        <?php
        /**
         * $postVm->getList() returns an array
         * getData('id') / getId() both works
         */
        ?>
        <?php foreach ($postVm->getList() as $post) : ?>
            <li>
                <a href="<?= $block->getUrl('blog/post/detail', ['id' => $post->getData('id')]) ?>">
                    <?= $post->getTitle() ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    <p><?= __('Post Count: %1', $postVm->getTotalPosts()) ?></p>
</div>