<?php

/**
 * Links in Magento template should be generated using a block helper function getUrl()
 * To get access to our IDE's intellisense functionality, we will need to typehint this variable at the top of our template file.
 *
 * @var Magento\Framework\View\Element\Template $block
 */
?>
<div class="blog-post-list">
    <!-- 
        Magento comes with a special PHP function we should pass all text through. 
        wrap this text in a short echo tag, and wrap it in this special function __()
        This function makes text translatable to many other languages. 
        Make it a practice to wrap all static texts this way
    -->
    <h1><?= __('Blog Post List'); ?></h1>
    <ul>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 1]) ?>">Post 1</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 2]) ?>">Post 2</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 3]) ?>">Post 3</a></li>
    </ul>
    <p><?= __('Post Count: %1', 3) ?></p>
</div>