<?php

/**
 * Links in Magento template should be generated using a block helper function getUrl()
 * To get access to our IDE's intellisense functionality, we will need to typehint this variable at the top of our template file.
 *
 * @var Magento\Framework\View\Element\Template $block
 * @var JonaM\Blog\ViewModel\Post $postVm
 */
$postVm = $block->getData('post_vm');
?>
<div class="blog-post-sidebar">
    <p><strong><?= __('Other Blog Posts'); ?></strong></p>
    <ul>
        <?php foreach ($postVm->getList() as $post) : ?>
            <li>
                <a href="<?= $block->getUrl('blog/post/detail', ['id' => $post->getData('id')]) ?>">
                    <?= $post->getTitle() ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>